/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardLivedemoRouteImport } from './routes/dashboard/livedemo'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardCreateRouteImport } from './routes/dashboard.create'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardActivityRouteImport } from './routes/dashboard/activity'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminChatbotsRouteImport } from './routes/admin.chatbots'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminChatbotsIdRouteImport } from './routes/admin.chatbots.$id'
import { Route as DashboardAgentsIdIndexRouteImport } from './routes/dashboard/agents/$id/index'
import { Route as DashboardAgentsIdSourcesRouteImport } from './routes/dashboard/agents/$id/sources'
import { Route as DashboardAgentsIdSettingsRouteImport } from './routes/dashboard/agents/$id/settings'
import { Route as DashboardAgentsIdEmbedTestRouteImport } from './routes/dashboard/agents/$id/embed-test'
import { Route as DashboardAgentsIdAnalyticsRouteImport } from './routes/dashboard/agents/$id/analytics'
import { Route as DashboardAgentsIdActivityRouteImport } from './routes/dashboard/agents/$id/activity'
import { Route as DashboardAgentsIdActionsRouteImport } from './routes/dashboard/agents/$id/actions'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLivedemoRoute = DashboardLivedemoRouteImport.update({
  id: '/livedemo',
  path: '/livedemo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatbotsRoute = AdminChatbotsRouteImport.update({
  id: '/chatbots',
  path: '/chatbots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminChatbotsIdRoute = AdminChatbotsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminChatbotsRoute,
} as any)
const DashboardAgentsIdIndexRoute = DashboardAgentsIdIndexRouteImport.update({
  id: '/agents/$id/',
  path: '/agents/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsIdSourcesRoute =
  DashboardAgentsIdSourcesRouteImport.update({
    id: '/agents/$id/sources',
    path: '/agents/$id/sources',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsIdSettingsRoute =
  DashboardAgentsIdSettingsRouteImport.update({
    id: '/agents/$id/settings',
    path: '/agents/$id/settings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsIdEmbedTestRoute =
  DashboardAgentsIdEmbedTestRouteImport.update({
    id: '/agents/$id/embed-test',
    path: '/agents/$id/embed-test',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsIdAnalyticsRoute =
  DashboardAgentsIdAnalyticsRouteImport.update({
    id: '/agents/$id/analytics',
    path: '/agents/$id/analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsIdActivityRoute =
  DashboardAgentsIdActivityRouteImport.update({
    id: '/agents/$id/activity',
    path: '/agents/$id/activity',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsIdActionsRoute =
  DashboardAgentsIdActionsRouteImport.update({
    id: '/agents/$id/actions',
    path: '/agents/$id/actions',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/chatbots': typeof AdminChatbotsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/livedemo': typeof DashboardLivedemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/chatbots/$id': typeof AdminChatbotsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/dashboard/agents/$id/actions': typeof DashboardAgentsIdActionsRoute
  '/dashboard/agents/$id/activity': typeof DashboardAgentsIdActivityRoute
  '/dashboard/agents/$id/analytics': typeof DashboardAgentsIdAnalyticsRoute
  '/dashboard/agents/$id/embed-test': typeof DashboardAgentsIdEmbedTestRoute
  '/dashboard/agents/$id/settings': typeof DashboardAgentsIdSettingsRoute
  '/dashboard/agents/$id/sources': typeof DashboardAgentsIdSourcesRoute
  '/dashboard/agents/$id/': typeof DashboardAgentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/enterprise': typeof EnterpriseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/chatbots': typeof AdminChatbotsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/livedemo': typeof DashboardLivedemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/chatbots/$id': typeof AdminChatbotsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/dashboard/agents/$id/actions': typeof DashboardAgentsIdActionsRoute
  '/dashboard/agents/$id/activity': typeof DashboardAgentsIdActivityRoute
  '/dashboard/agents/$id/analytics': typeof DashboardAgentsIdAnalyticsRoute
  '/dashboard/agents/$id/embed-test': typeof DashboardAgentsIdEmbedTestRoute
  '/dashboard/agents/$id/settings': typeof DashboardAgentsIdSettingsRoute
  '/dashboard/agents/$id/sources': typeof DashboardAgentsIdSourcesRoute
  '/dashboard/agents/$id': typeof DashboardAgentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/chatbots': typeof AdminChatbotsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/livedemo': typeof DashboardLivedemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/chatbots/$id': typeof AdminChatbotsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/dashboard/agents/$id/actions': typeof DashboardAgentsIdActionsRoute
  '/dashboard/agents/$id/activity': typeof DashboardAgentsIdActivityRoute
  '/dashboard/agents/$id/analytics': typeof DashboardAgentsIdAnalyticsRoute
  '/dashboard/agents/$id/embed-test': typeof DashboardAgentsIdEmbedTestRoute
  '/dashboard/agents/$id/settings': typeof DashboardAgentsIdSettingsRoute
  '/dashboard/agents/$id/sources': typeof DashboardAgentsIdSourcesRoute
  '/dashboard/agents/$id/': typeof DashboardAgentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/enterprise'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/solutions'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/chatbots'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/create'
    | '/dashboard/integrations'
    | '/dashboard/livedemo'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/chatbots/$id'
    | '/admin/users/$id'
    | '/dashboard/agents/$id/actions'
    | '/dashboard/agents/$id/activity'
    | '/dashboard/agents/$id/analytics'
    | '/dashboard/agents/$id/embed-test'
    | '/dashboard/agents/$id/settings'
    | '/dashboard/agents/$id/sources'
    | '/dashboard/agents/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/enterprise'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/solutions'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/chatbots'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/create'
    | '/dashboard/integrations'
    | '/dashboard/livedemo'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/chatbots/$id'
    | '/admin/users/$id'
    | '/dashboard/agents/$id/actions'
    | '/dashboard/agents/$id/activity'
    | '/dashboard/agents/$id/analytics'
    | '/dashboard/agents/$id/embed-test'
    | '/dashboard/agents/$id/settings'
    | '/dashboard/agents/$id/sources'
    | '/dashboard/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/enterprise'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/solutions'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/chatbots'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/create'
    | '/dashboard/integrations'
    | '/dashboard/livedemo'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/chatbots/$id'
    | '/admin/users/$id'
    | '/dashboard/agents/$id/actions'
    | '/dashboard/agents/$id/activity'
    | '/dashboard/agents/$id/analytics'
    | '/dashboard/agents/$id/embed-test'
    | '/dashboard/agents/$id/settings'
    | '/dashboard/agents/$id/sources'
    | '/dashboard/agents/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EnterpriseRoute: typeof EnterpriseRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/livedemo': {
      id: '/dashboard/livedemo'
      path: '/livedemo'
      fullPath: '/dashboard/livedemo'
      preLoaderRoute: typeof DashboardLivedemoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatbots': {
      id: '/admin/chatbots'
      path: '/chatbots'
      fullPath: '/admin/chatbots'
      preLoaderRoute: typeof AdminChatbotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/chatbots/$id': {
      id: '/admin/chatbots/$id'
      path: '/$id'
      fullPath: '/admin/chatbots/$id'
      preLoaderRoute: typeof AdminChatbotsIdRouteImport
      parentRoute: typeof AdminChatbotsRoute
    }
    '/dashboard/agents/$id/': {
      id: '/dashboard/agents/$id/'
      path: '/agents/$id'
      fullPath: '/dashboard/agents/$id/'
      preLoaderRoute: typeof DashboardAgentsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/$id/sources': {
      id: '/dashboard/agents/$id/sources'
      path: '/agents/$id/sources'
      fullPath: '/dashboard/agents/$id/sources'
      preLoaderRoute: typeof DashboardAgentsIdSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/$id/settings': {
      id: '/dashboard/agents/$id/settings'
      path: '/agents/$id/settings'
      fullPath: '/dashboard/agents/$id/settings'
      preLoaderRoute: typeof DashboardAgentsIdSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/$id/embed-test': {
      id: '/dashboard/agents/$id/embed-test'
      path: '/agents/$id/embed-test'
      fullPath: '/dashboard/agents/$id/embed-test'
      preLoaderRoute: typeof DashboardAgentsIdEmbedTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/$id/analytics': {
      id: '/dashboard/agents/$id/analytics'
      path: '/agents/$id/analytics'
      fullPath: '/dashboard/agents/$id/analytics'
      preLoaderRoute: typeof DashboardAgentsIdAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/$id/activity': {
      id: '/dashboard/agents/$id/activity'
      path: '/agents/$id/activity'
      fullPath: '/dashboard/agents/$id/activity'
      preLoaderRoute: typeof DashboardAgentsIdActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/$id/actions': {
      id: '/dashboard/agents/$id/actions'
      path: '/agents/$id/actions'
      fullPath: '/dashboard/agents/$id/actions'
      preLoaderRoute: typeof DashboardAgentsIdActionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminChatbotsRouteChildren {
  AdminChatbotsIdRoute: typeof AdminChatbotsIdRoute
}

const AdminChatbotsRouteChildren: AdminChatbotsRouteChildren = {
  AdminChatbotsIdRoute: AdminChatbotsIdRoute,
}

const AdminChatbotsRouteWithChildren = AdminChatbotsRoute._addFileChildren(
  AdminChatbotsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminChatbotsRoute: typeof AdminChatbotsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminChatbotsRoute: AdminChatbotsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardLivedemoRoute: typeof DashboardLivedemoRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAgentsIdActionsRoute: typeof DashboardAgentsIdActionsRoute
  DashboardAgentsIdActivityRoute: typeof DashboardAgentsIdActivityRoute
  DashboardAgentsIdAnalyticsRoute: typeof DashboardAgentsIdAnalyticsRoute
  DashboardAgentsIdEmbedTestRoute: typeof DashboardAgentsIdEmbedTestRoute
  DashboardAgentsIdSettingsRoute: typeof DashboardAgentsIdSettingsRoute
  DashboardAgentsIdSourcesRoute: typeof DashboardAgentsIdSourcesRoute
  DashboardAgentsIdIndexRoute: typeof DashboardAgentsIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardLivedemoRoute: DashboardLivedemoRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAgentsIdActionsRoute: DashboardAgentsIdActionsRoute,
  DashboardAgentsIdActivityRoute: DashboardAgentsIdActivityRoute,
  DashboardAgentsIdAnalyticsRoute: DashboardAgentsIdAnalyticsRoute,
  DashboardAgentsIdEmbedTestRoute: DashboardAgentsIdEmbedTestRoute,
  DashboardAgentsIdSettingsRoute: DashboardAgentsIdSettingsRoute,
  DashboardAgentsIdSourcesRoute: DashboardAgentsIdSourcesRoute,
  DashboardAgentsIdIndexRoute: DashboardAgentsIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EnterpriseRoute: EnterpriseRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
